# users/deepwatrcreatur/hosts/homeserver/justfile

update dir="/home/deepwatrcreatur/flakes/unified-nix-configuration":
  sudo nixos-rebuild switch --flake {{dir}}#nixos_lxc

nh-update dir="/home/deepwatrcreatur/flakes/unified-nix-configuration":
  nix --experimental-features 'nix-command flakes' run 'github:viperML/nh' -- os switch {{dir}}