# users/deepwatrcreatur/hosts/workstation/justfile

update:
  sudo nixos-rebuild switch --flake /home/deepwatrcreatur/unified-nix-configuration#workstation

nh-update:
  nh os switch /home/deepwatrcreatur/unified-nix-configuration#workstation