# users/deepwatrcreatur/hosts/cache-build-server/justfile

update dir="/home/deepwatrcreatur/unified-nix-configuration":
  sudo nixos-rebuild switch --flake {{dir}}#{{`hostname`}}

nh-update dir="/home/deepwatrcreatur/unified-nix-configuration":
  nh os switch {{dir}}#{{`hostname`}}
