# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ modulesPath, pkgs, ... }:

{
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    #./lxd.nix
   
  ];

  environment.shells = with pkgs; [ bashInteractive ];
  environment.systemPackages = with pkgs; [ busybox coreutils ];
  system.activationScripts.binBashSymlink.text = ''
    ln -sf /run/current-system/sw/bin/bash /bin/bash
    ln -sf /run/current-system/sw/bin/bash /bin/sh
  '';
  environment.extraInit = ''
    export PATH=/run/current-system/sw/bin:/usr/bin:/bin
  '';  

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  system.stateVersion = "25.05"; # Did you read the comment?
}
