# modules/home-manager/sops-deepwatrcreatur.nix
# This module configures sops for deepwatrcreatur within Home Manager.
{ config, lib, pkgs, inputs, ... }: # Module arguments

# The entire module (the attribute set containing options, imports, and config)
# is conditionally generated by lib.mkIf.
lib.mkIf config.my.sops.enable { # <--- This is the single top-level expression

  # Options declaration must be *inside* this top-level attribute set.
  options = {
    my.sops.enable = lib.mkEnableOption "Sops integration for home-manager user";
  };

  # Imports must also be inside this top-level attribute set.
  imports = [ inputs.sops-nix.homeManagerModules.sops ];

  let
    sopsSecretsDir = toString (builtins.path { path = ./../../secrets; });
  in

  # The 'config' attribute
  config = {
    home.packages = [ pkgs.sops ];

    home.file."${config.xdg.configHome}/sops/.sops.yaml" = {
      source = "${sopsSecretsDir}/.sops.yaml";
      mode = "0400";
    };

    # Uncomment and configure your sops.secrets entries as needed
    # sops.secrets."git-signing-key" = {
    #   sopsFile = "${sopsSecretsDir}/user-secrets/deepwatrcreatur-git-keys.yaml.enc";
    #   key = "gpg_signing_key";
    #   path = "${config.xdg.configHome}/git/gpg-signing-key.asc";
    #   mode = "0600";
    # };
  };
}
