
update:
  darwin-rebuild switch --flake /Volumes/Work/unified-nix-configuration#macminim4

nh-update:
  nh darwin switch --extra-experimental-features "nix-command flakes" /Volumes/Work/unified-nix-configuration
