{ config, lib, pkgs, ... }:

{
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      dns_enabled = true;
    };
  };

  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  systemd.tmpfiles.rules = [
    "d /var/lib/homebridge/volumes/homebridge 0755 1000 1000 - -"
  ];

  virtualisation.oci-containers.containers."homebridge-homebridge" = {
    image = "homebridge/homebridge:latest";
    volumes = [
      "/var/lib/homebridge/volumes/homebridge:/homebridge:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };

  systemd.services."podman-homebridge-homebridge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-homebridge-root.target"
    ];
    wantedBy = [
      "podman-compose-homebridge-root.target"
    ];
  };

  systemd.targets."podman-compose-homebridge-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
